name: FirstPlugins
version: '${version}'
main: io.github.eggest.firstplugins.FirstPlugins
api-version: '1.19'
author: Eggest6973
description: Eggest6973的第一个插件
website: eggest.github.io
commands:
  diamond:
    description: Give you 64 diamond block
    usage: /diamond
  die:
    description: kill yourself
    usage: /die
  regeneration:
    description: regeneration
    usage: /regeneration

